### ISSUE TITLE
New Characters

### ISSUE THREAD

**Issue by RedEdge967** [mgechev/mk.js#17]
## Hey @mgechev !!!
Your work is so cool. and I really enjoyed it. as a mortal kombat fan, if you can, please add more characters like Scorpian, Jax, Kung lao or Liu kang. btw your work is cool. thank you for creating it.

**Comment by mgechev** [comment]
Hey @RedEdge967 feel free to open a PR with the change :)

**Comment by RedEdge967** [comment]
I will try @mgechev
